import * as axe from 'axe-core';
import { cleanup, render, type RenderResult } from '@testing-library/react';
import { afterEach } from 'vitest';

import { Keypair, StrKey } from '@stellar/stellar-sdk';
import type { ReactElement } from 'react';

import type { WalletController } from '../hooks/useWallet';
import type { ContractClient, SubmitResult } from '../lib/contract';
import type { FeeRecord } from '../lib/fee';
import type { AppConfig } from '../lib/network';
import type { PageProps } from '../pages/shared';

// RTL's auto-cleanup registers via the global afterEach, which vitest does not
// enable with globals: false, so run it here for every render test.
afterEach(() => {
  cleanup();
});

/**
 * Renders into happy-dom (act-safe, via RTL) and runs the axe-core
 * accessibility check, rejecting on serious or critical violations.
 */
export async function renderWithA11y(ui: ReactElement): Promise<RenderResult> {
  const result = render(ui);
  const results = await axe.run(result.container, {
    resultTypes: ['violations'],
    // Stylesheets are not loaded in the test DOM, so axe cannot compute real
    // contrast ratios here; contrast is covered by the design tokens, which
    // were measured by hand (accessibility audit A11Y-04).
    rules: { 'color-contrast': { enabled: false } },
  });
  const serious = results.violations.filter(
    (v) => v.impact === 'serious' || v.impact === 'critical',
  );
  if (serious.length > 0) {
    throw new Error(
      `axe found ${serious.length} serious/critical violations: ` +
        serious
          .map((v) => `${v.id}: ${v.nodes.map((n) => n.target.join(' ')).join(', ')}`)
          .join('; '),
    );
  }
  return result;
}

/**
 * Renders and returns the queries, skipping the accessibility check — for
 * tests that assert something axe would legitimately flag elsewhere in the
 * fixture, or where the a11y check is covered by another test.
 */
export function renderOnly(ui: ReactElement): RenderResult {
  return render(ui);
}

/**
 * Queries text across the container, including inside hidden (sr-only) nodes.
 * happy-dom keeps clipped content in the DOM and in textContent, so the
 * sr-only additions are assertable here.
 */
export function textOf(container: HTMLElement): string {
  return container.textContent ?? '';
}

/**
 * A fake account address, generated by the real SDK so it passes the same
 * StrKey checksum validation the app applies. Random, never a real account,
 * and never derived from any personal data.
 */
export function fakeAccount(_seed = 0): string {
  return Keypair.random().publicKey();
}

/**
 * A fake contract id, encoded by the real SDK so it passes StrKey validation.
 * The seed fills the 32-byte payload deterministically; it is not a real
 * contract on any network.
 */
export function fakeContractId(seed = 0): string {
  return StrKey.encodeContract(new Uint8Array(32).fill(seed & 0xff));
}

const FAKE_HASH = 'a'.repeat(64);

/** Builds a FeeRecord with fake addresses and a synthetic reference. */
export function feeFactory(overrides: Partial<FeeRecord> = {}): FeeRecord {
  const reference = new Uint8Array(32);
  for (let i = 0; i < 32; i++) reference[i] = (i * 7 + 3) % 256;
  return {
    id: 1n,
    school: fakeAccount(1),
    token: fakeContractId(2),
    reference,
    total: 5000n,
    dueAt: 4102444800n, // 2100-01-01, far in the future for status tests.
    paidTotal: 0n,
    refundedTotal: 0n,
    closed: false,
    ...overrides,
  };
}

/** A connected, testnet wallet double with no real address. */
export function walletFactory(overrides: Partial<WalletController> = {}): WalletController {
  return {
    address: fakeAccount(3),
    connecting: false,
    error: null,
    onTestnet: true,
    connect: async () => {},
    disconnect: async () => {},
    refreshNetwork: async () => true,
    ...overrides,
  };
}

/** A valid-in-shape AppConfig pointing at localhost — never used on air. */
export function configFactory(overrides: Partial<AppConfig> = {}): AppConfig {
  return {
    network: 'testnet',
    passphrase: 'Test SDF Network ; September 2015',
    rpcUrl: 'http://127.0.0.1:8000',
    contractId: fakeContractId(4),
    explorerBaseUrl: 'https://example.testexplorer.invalid',
    ...overrides,
  };
}

/**
 * A ContractClient double. Reads are answered from `fees` by id; writes return
 * a fake hash. No method reaches a network.
 */
export function clientFactory(fees: FeeRecord[] = []): ContractClient & {
  failNextWriteWith: (error: unknown) => void;
} {
  const byId = new Map(fees.map((fee) => [fee.id, fee]));
  let writeFailure: unknown = null;

  const submit = async (): Promise<SubmitResult> => {
    if (writeFailure !== null) {
      const error = writeFailure;
      writeFailure = null;
      throw error;
    }
    return { hash: FAKE_HASH };
  };

  return {
    async getFee(_source, feeId) {
      const fee = byId.get(feeId);
      if (fee === undefined) throw new Error("We couldn't find that fee.");
      return fee;
    },
    async getStatus(_source, feeId) {
      const fee = byId.get(feeId);
      if (fee === undefined) throw new Error("We couldn't find that fee.");
      return fee.closed ? 'Closed' : 'Open';
    },
    async prepareCreateFee() {
      return { xdr: 'fake-xdr' };
    },
    async preparePay() {
      return { xdr: 'fake-xdr' };
    },
    async prepareRefund() {
      return { xdr: 'fake-xdr' };
    },
    async prepareCloseFee() {
      return { xdr: 'fake-xdr' };
    },
    submit,
    failNextWriteWith(error: unknown) {
      writeFailure = error;
    },
  };
}

/** PageProps assembled from the doubles, ready to spread into a page. */
export function pagePropsFactory(
  options: {
    client?: ContractClient;
    config?: AppConfig;
    wallet?: WalletController;
  } = {},
): PageProps {
  return {
    client: options.client ?? clientFactory([]),
    config: options.config ?? configFactory(),
    wallet: options.wallet ?? walletFactory(),
  };
}
